create table if not exists public.practice_attempts (
  id bigint generated by default as identity primary key,
  exercise_id text not null,
  category text not null,
  correct boolean not null,
  answer_text text,
  created_at timestamptz not null default now()
);

alter table public.practice_attempts enable row level security;

grant insert on table public.practice_attempts to anon, authenticated;
grant usage, select on sequence public.practice_attempts_id_seq to anon, authenticated;

create policy "allow anonymous practice logging"
on public.practice_attempts
for insert
to anon, authenticated
with check (
  char_length(exercise_id) between 1 and 80
  and char_length(category) between 1 and 40
  and coalesce(char_length(answer_text), 0) <= 300
);

create index if not exists practice_attempts_created_at_idx on public.practice_attempts (created_at desc);
create index if not exists practice_attempts_category_idx on public.practice_attempts (category);
